cc_binary(
    name='main',
    srcs=['main.cc'],
    deps=['//logger:logger', '//util/time:time'],
    optimize=['-O1'],
)

cc_binary(
    name='test',
    srcs=['test.cc'],
    deps=['//logger:logger'],
    optimize=['-O1'],
)
