cc_test(
    name='unmarshal_test',
    srcs=[
        'unmarshal_test.cc',
    ],
    deps=[
        '//json_helper:json_helper',
        '//thirdparty/gtest:gtest',
    ],
    defs=['_JSON_HELPER_DEBUG=true'],
)

cc_test(
    name='json_helper_test',
    srcs=[
        'json_helper_test.cc',
    ],
    deps=[
        '//json_helper:json_helper',
        '//thirdparty/gtest:gtest',
    ],
    defs=['_JSON_HELPER_DEBUG=true'],
)


cc_test(
    name='marshal_test',
    srcs=[
        'marshal_test.cc',
    ],
    deps=[
        '//json_helper:json_helper',
        '//thirdparty/gtest:gtest',
    ],
    defs=['_JSON_HELPER_DEBUG=true'],
)
